blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/5NsYYuvm7D
    about: Have questions or need support but can't find the discussions page? Feel free to join my development Discord.