name: Feature Request
description: Suggest a new feature
labels: [enhancement]
assignees: Glazelf
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature. Description should go into as much detail as possible. Feel free to add screenshots.
    validations:
      required: true